# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-20 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190119_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.TextField(default=b'https://api.adorable.io/avatars/285/i.png'),
        ),
    ]
