# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-20 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(default=b'https://cdn.pixabay.com/photo/2016/08/04/10/37/office-1568780_960_720.jpg'),
        ),
    ]
