# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-01-20 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(blank=True, default=b'https://api.adorable.io/avatars/285/i.png'),
        ),
    ]
